# Generated by Django 2.1 on 2018-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='midia'),
        ),
    ]
