# Generated by Django 2.1 on 2018-08-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_filmes_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='filmes',
            new_name='Animacao',
        ),
    ]
