# Generated by Django 2.1 on 2018-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0003_auto_20180816_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animacao',
            options={'verbose_name_plural': 'Animações'},
        ),
        migrations.RenameField(
            model_name='animacao',
            old_name='genero',
            new_name='filme',
        ),
        migrations.RenameField(
            model_name='animacao',
            old_name='photo',
            new_name='imagem',
        ),
    ]
