# Generated by Django 2.1 on 2018-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0004_auto_20180816_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=60)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='midia')),
            ],
        ),
    ]
