# Generated by Django 2.1 on 2018-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0005_terror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terror',
            options={'verbose_name_plural': 'Terror'},
        ),
        migrations.AddField(
            model_name='animacao',
            name='nota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terror',
            name='nota',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
