# Generated by Django 2.1 on 2018-08-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0007_comedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comedia',
            options={},
        ),
    ]
