# Generated by Django 2.1 on 2018-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0008_auto_20180821_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comedia',
            options={'verbose_name_plural': 'Comédias'},
        ),
    ]
